clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 93.77.181.213

vector:
  hosts:
    vector-01:
      ansible_host: 93.77.181.166

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 93.77.178.100

all:
  vars:
    ansible_user: yc-user
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_password: ""
    ansible_become_flags: "-n"